### ISSUE TITLE
https://demotiles.maplibre.org/style.json get req not working in dev enviorment

### ISSUE THREAD

**Issue by prantikseal** [maplibre/demotiles#17]
My internet connection is good and I am using the latest version of chrome but it shows me this

![image](https://github.com/maplibre/demotiles/assets/83081442/cfc142b5-a976-4d8f-b78a-59aaac881b53)

**Comment by prantikseal** [comment]
I tried other browsers, used a different network connection, but it seems to give me the same error. the map only loaded when I used maptiler as the style library. I need help with this

**Comment by prantikseal** [comment]
https://api.maptiler.com/maps/streets-v2/style.json this one

**Comment by birkskyum** [comment]
Hit this one today as well with some demotiles terrain-tiles

**Comment by prantikseal** [comment]
how can this be fixed @birkskyum then I guess it a server issue and not the dev enviornment?

**Comment by birkskyum** [comment]
Can you hit the url directly? https://demotiles.maplibre.org/style.json

**Comment by birkskyum** [comment]
When I go to the github pages settings it says "DNS Check in Progress"... will keep an eye on it and try to figure out if there has been introduced a dns restrictions anywhere. I am able to load some demotiles files locally though, so it's more flaky than consistently blocking.

**Comment by birkskyum** [comment]
Figured out my issue - I was just making a wrong request outside of the covered bbox. Seems to work from localhost, tiles, terrain-tiles, style.json etc..

**Comment by prantikseal** [comment]
> Can you hit the url directly? https://demotiles.maplibre.org/style.json

I did the same, main problem that I faced the website loads sometimes it doesnt says cant be reached. even if my internet is stable.

**Comment by prantikseal** [comment]
Tried other demotiles as well, seems to give me the same issue..

**Comment by birkskyum** [comment]
I believe it's beyond our control. Do you have a VPN active for this?
