### ISSUE TITLE
Style license

### ISSUE THREAD

**Issue by m0nac0** [maplibre/demotiles#2]
I'd like to use this example style for my flutter MapLibre plugin (https://github.com/m0nac0/flutter-maplibre-gl), e.g. to have a style without access token for the CI.

 I noticed, however, that the style.json contains the line:

> "maptiler:copyright": "This style was generated on MapTiler Cloud. Usage outside of MapTiler Cloud or MapTiler Server requires valid MapTiler Data package: https://www.maptiler.com/data/ -- please contact us.",

Which seems to conflict with the BSD-3-Clause License of this repo. It would be great, if you could clarify whether it's actually okay to use this style.

**Comment by wipfli** [comment]
@klokan @petr-pokorny-1 please clarify.

**Comment by petr-pokorny-1** [comment]
I believe it is OK (i think we should remove "maptiler:copyright":) - but I will wait @klokan to confirm it.

**Comment by klokan** [comment]
Confirmed

**Comment by m0nac0** [comment]
That's great to hear! Would it be possible to adapt the relevant section of the file?

**Comment by wipfli** [comment]
Sure. Feel free to send a pull request.
