### ISSUE TITLE
demotiles.maplibre.org/font/Open Sans Bold,Arial Unicode MS Bold/0-255.pbf => 404 Not Found

### ISSUE THREAD

**Issue by astridx** [maplibre/demotiles#4]
I have modified the plugin `github.com/mapbox/mapbox-gl-directions` to use OSRM and Nominatim. No token is required for this. 

You can see the draft here: https://github.com/astridx/maplibre-gl-directions/

Now I would also like to include an example with this demotiles, because this way I don't need a token at all.

You can finde my example code here:

https://github.com/astridx/maplibre-gl-directions/blob/d93cecdaeb036ebb686f44cfa9e909c079fd8f81/example/maplibre-gl-directions.html#L48

When I use Maptiler tiles, it looks like this.
![a1](https://user-images.githubusercontent.com/9974686/139581074-d8fb8e26-40c4-4e33-8893-02c9a796d5b7.PNG)

With the demotiles I see that
![a2](https://user-images.githubusercontent.com/9974686/139581076-ef53224d-12b3-441a-bd06-34328eddd731.PNG)

I realise that the example is not meaningful because you only see the orange background. But the route should still be displayed, right? If I interpret this correctly, an error occurs because the letters A and B for the starting point and the end point are not found. Am I doing something wrong?

**Comment by wipfli** [comment]
Can you change the font? Can you use one stored in https://github.com/maplibre/demotiles/tree/gh-pages/font?

**Comment by astridx** [comment]
Yes, thank you very much. I could have thought of that myself
