### ISSUE TITLE
MapLibre Main page shows Crimea as Russia

### ISSUE THREAD

**Issue by jelenjelinek** [maplibre/demotiles#8]
MapLibre Mainpage shows Crimea as Russia (https://maplibre.com/),
despite it being still officially a Ukrainian territory and despite the fact
that the MapLibre logo contains the Ukrainian flag as a symbol of Support.
This creates a very poor PR image for the whole Project.

![1](https://user-images.githubusercontent.com/87318027/185746245-9b496f83-be12-4fce-b8d6-29148840ef62.png)

**Comment by wipfli** [comment]
Thanks for reporting @jelenjelinek. See #9
